language: android

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/5036
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  - ./gradlew clean test

after_success:
  - ./gradlew jacocoTestReport
